name: worktimes_new
description: "A new Flutter project."


version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5  # Aktualisiere auf die neueste Version
  intl: ^0.20.1
  sqflite: ^2.4.1
  path: ^1.9.0
  shared_preferences: ^2.3.5
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.14.1"
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 24
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/icon.png"

