import 'package:get/get.dart';

class LocalString extends Translations {
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'Your working times': 'Your working times',
          'Enter your Name': 'Enter your Name',
          'Enter name of employer': 'Enter name of employer',
          'Save': 'Save',
          'Change employer': 'Change employer',
          'Please enter your new employer:': 'Please enter your new employer:',
          'New employer': 'New employer',
          'Cancel': 'Cancel',
          'Confirm deletion': 'Confirm deletion',
          'Do you really want to delete this entry?':
              'Do you really want to delete this entry?',
          'Delete': 'Delete',
          'Time Entries': 'Time Entries',
          'Select Month': 'Select Month',
          'Done': 'Done',
          'January': 'January',
          'February': 'February',
          'March': 'March',
          'April': 'April',
          'May': 'May',
          'June': 'June',
          'July': 'July',
          'August': 'August',
          'September': 'September',
          'October': 'October',
          'November': 'November',
          'December': 'December',
          'Wage Calculation': 'Wage Calculation',
          'Wage calculation': 'Wage calculation',
          'Change Language': 'Change Language',
          'Hourly wage': 'Hourly wage',
          'Late shift bonus in %': 'Late shift bonus in %',
          'Night shift bonus in %': 'Night shift bonus in %',
          'Late shift starts at (hour)': 'Late shift starts at (hour)',
          'Night shift starts at (hour)': 'Night shift starts at (hour)',
          'Wage for:': 'Wage for:',
          'Hourly wage is 0': 'Hourly wage is 0',
          'Calculate': 'Calculate',
          'Break times saved successfully!': 'Break times saved successfully!',
          'Insert breaks': 'Insert breaks',
          'Early shift break': 'Early shift break',
          'Late shift break': 'Late shift break',
          'Night shift break': 'Night shift break',
          'No time selected': 'No time selected',
          'Select Start Time': 'Select Start Time',
          'Select End Time': 'Select End Time',
          'Monday': 'Monday',
          'Tuesday': 'Tuesday',
          'Wednesday': 'Wednesday',
          'Thursday': 'Thursday',
          'Friday': 'Friday',
          'Saturday': 'Saturday',
          'Sunday': 'Sunday',
          'Time entry': 'Time entry',
          'Select Shift': 'Select Shift',
          'Early Shift': 'Early Shift',
          'Late Shift': 'Late Shift',
          'Night Shift': 'Night Shift',
          'Add': 'Add',
          'Add breaks': 'Add breaks',
          'Show Entries': 'Show Entries',
          'Choose language': 'Choose language',
          'Duration:': 'Duration:',
          'Date:': 'Date:',
          'Start:': 'Start:',
          'End:': 'End:',
          'Shift:': 'Shift:',
          'Edit entry:': 'Edit entry:'

        },
        'de_Gr': {
          'Your working times': 'Ihre Arbeitszeiten',
          'Enter your Name': 'Geben Sie Ihren Namen ein',
          'Enter name of employer': 'Name des Arbeitgebers eingeben',
          'Save': 'Speichern',
          'Change employer': 'Arbeitgeber wechseln',
          'Please enter your new employer:':
              'Bitte geben Sie Ihren neuen Arbeitgeber an:',
          'New employer': 'Neuer Arbeitgeber',
          'Cancel': 'Abbrechen',
          'Confirm deletion': 'Entfernen Bestätigen',
          'Do you really want to delete this entry?':
              'Wollen Sie diesen Eintrag wirklich entfernen?',
          'Delete': 'Entfernen',
          'Time Entries': 'Zeiteinträge',
          'Select Month': 'Monat auswählen',
          'Done': 'Fertig',
          'January': 'Januar',
          'February': 'Februar',
          'March': 'März',
          'April': 'April',
          'May': 'Mai',
          'June': 'Juni',
          'July': 'Juli',
          'August': 'August',
          'September': 'September',
          'October': 'Oktober',
          'November': 'November',
          'December': 'Dezember',
          'Wage Calculation': 'Berechnung der Löhne',
          'Wage calculation': 'Berechnung der Löhne',
          'Change Language': 'Sprache Wechseln',
          'Hourly wage': 'Stundenlohn',
          'Late shift bonus in %': 'Spätschicht bonus in %',
          'Night shift bonus in %': 'Nachtschicht bonus in %',
          'Late shift starts at (hour)': 'Spätschicht fängt um (Uhrzeit) an',
          'Night shift starts at (hour)': 'Nachtschicht fängt am (Uhrzeit) an',
          'Wage for:': 'Lohn für den:',
          'Hourly wage is 0': 'Der Stundenlohn beträgt 0',
          'Calculate': 'Rechnen',
          'Break times saved successfully!':
              'Pausenzeiten erfolgreich gespeichert!',
          'Insert breaks': 'Pausen eintragen',
          'Early shift break': 'Frühschichtpause',
          'Late shift break': 'Spätschichtpause',
          'Night shift break': 'Nachtschichtpause',
          'No time selected': 'Keine Zeit ausgewählt',
          'Select Start Time': 'Startzeit wählen',
          'Select End Time': 'Endzeit wählen',
          'Monday': 'Montag',
          'Tuesday': 'Dienstag',
          'Wednesday': 'Mittwoch',
          'Thursday': 'Donnerstag',
          'Friday': 'Freitag',
          'Saturday': 'Samstag',
          'Sunday': 'Sonntag',
          'Time entry': 'Zeiteintragung',
          'Select Shift': 'Schicht wählen',
          'Early Shift': 'Frühschicht',
          'Late Shift': 'Spätschicht',
          'Night Shift': 'Nachtschicht',
          'Add': 'Hinzufügen',
          'Add breaks': 'Pausen festlegen',
          'Show Entries': 'Einträge anzeigen',
          'Choose language': 'Sprache wählen',
          'Duration:': 'Dauer:',
          'Date:': 'Datum:',
          'Start:': 'Start:',
          'End:': 'Ende:',
          'Shift:': 'Schicht:',
          'Edit entry:': 'Einträge Bearbeiten'
        },
        'ar_AR': {
          'Your working times': 'أوقات عملك',
          'Enter your Name': 'أدخل اسمك',
          'Enter name of employer': 'أدخل اسم جهة العمل',
          'Save': 'حفظ',
          'Change employer': 'تغيير جهة العمل',
          'Please enter your new employer:': 'أدخل اسم جهة العمل الجديد:',
          'New employer': 'جهة العمل الجديد',
          'Cancel': 'إلغاء',
          'Confirm deletion': 'تأكيد الحذف',
          'Do you really want to delete this entry?':
              'هل تريد حقاً حذف هذا الإدخال؟',
          'Delete': 'حذف',
          'Time Entries': 'إدخالات الوقت',
          'Select Month': 'حدد الشهر',
          'Done': 'تم',
          'January': 'ياناير',
          'February': 'فبراير',
          'March': 'مارس',
          'April': 'ابريل',
          'May': 'مايو',
          'June': 'يونيو',
          'July': 'يوليو',
          'August': 'اغسطس',
          'September': 'سبتمبر',
          'October': 'اكتوبر',
          'November': 'نوفمبر',
          'December': 'ديسمبر',
          'Wage Calculation': 'حساب الأجرة',
          'Wage calculation': 'حساب الأجرة',
          'Change Language': 'تغيير اللغة',
          'Hourly wage': 'الأجر بالساعة',
          'Late shift bonus in %': '% مكافأة المناوبة المسائية',
          'Night shift bonus in %': '% مكافأة المناوبة الليلية',
          'Late shift starts at (hour)': 'تبدأ المناوبة المسائية في (الساعة)',
          'Night shift starts at (hour)': 'تبدأ المناوبة الليلية في (الساعة)',
          'Wage for:': 'أجرة شهر:',
          'Hourly wage is 0': 'حساب الأجرة 0',
          'Calculate': 'احسب',
          'Break times saved successfully!': 'تم حفظ أوقات الراحة بنجاح!',
          'Insert breaks': 'إدراج أوقات الراحة',
          'Early shift break': 'راحة صباحية',
          'Late shift break': 'راحة مسائية',
          'Night shift break': 'راحة ليلية',
          'No time selected': 'لم يتم تحديد وقت',
          'Select Start Time': 'حدد وقت البدء',
          'Select End Time': 'حدد وقت الانتهاء',
          'Monday': 'الإثنين',
          'Tuesday': 'الثلاثاء',
          'Wednesday': 'الأربعاء',
          'Thursday': 'الخميس',
          'Friday': 'الجمعة',
          'Saturday': 'السبت',
          'Sunday': 'الأحد',
          'Time entry': 'إدخال الوقت',
          'Select Shift': 'اختر الفترة',
          'Early Shift': 'فترة صباحبة',
          'Late Shift': 'فترة مسائية',
          'Night Shift': 'فترةليلية',
          'Add': 'أضف',
          'Add breaks': 'تثبيت وقت الراحة',
          'Show Entries': 'عرض المداخلات',
          'Choose language': 'اختر اللغة',
          'Duration:': 'المدة:',
          'Date:': 'التاريخ:',
          'Start:': 'البدء:',
          'End:': 'الانتهاء:',
          'Shift:': 'المناوبة:',
          'Edit entry:': 'تعديل المدخلات:'
        }
      };
}
